#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import functions as f
import matplotlib.pyplot as plt
import pandas as pd

parser = argparse.ArgumentParser(description='''
Abund - Produces an Abundance/Relative abundance plot of a given dataset
''')
parser.add_argument('subject')
known, unknown = parser.parse_known_args()
known = {k: v for k, v in vars(known).items() if v is not None}
unknown = eval(unknown[0]) if unknown != [] else {}

f.setupplot()
subject = known.get("subject")
df = f.load(subject)
output = f.abund(df, **unknown)
plt.savefig(f'../results/{subject}abund.svg')
plt.show()
