#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import functions as f
import matplotlib.pyplot as plt
import pandas as pd

parser = argparse.ArgumentParser(description='''
Bar - Produces a barplot of a given dataset
''')

parser.add_argument('subject')
parser.add_argument('-x')
parser.add_argument('-y')
parser.add_argument('-hue')

known, unknown = parser.parse_known_args()
known = {k: v for k, v in vars(known).items() if v is not None}
unknown = eval(unknown[0]) if unknown != [] else {}


f.setupplot()
subject = known.get("subject")
df = f.load(subject)

#output = f.bar(df, **known|unknown)
output = f.bar(df, **known)
plt.savefig(f'../results/{subject}bar.svg')
plt.show()
