#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import matplotlib.pyplot as plt
import argparse
import sys
import utils

def PERMANOVA(df, meta):
    import pandas as pd
    from skbio.stats.distance import permanova
    from skbio import DistanceMatrix
    from scipy.spatial import distance
    beta = pd.DataFrame(
        distance.squareform(distance.pdist(df, metric="braycurtis")),
        columns=df.index,
        index=df.index) pvals = permanova(DistanceMatrix(beta, beta.index), meta) return pvals

def richness(df, axis=1):
    import numpy as np
    return df.agg(np.count_nonzero, axis=axis)

def evenness(df, axis=1):
    from skbio.diversity.alpha import pielou_e
    return df.agg(pielou_e, axis=axis)

def shannon(df, axis=1):
    from skbio.diversity.alpha import shannon
    return df.agg(shannon, axis=axis)

def diversity(df, subject):
    import pandas as pd
    import numpy as np
    diversity = pd.concat(
            [evenness(df),
             richness(df),
             shannon(df)],
            axis=1).sort_index().sort_index(ascending=False)
    diversity.droplevel(1).to_csv(f'../results/{subject}Diversity.csv')
    diversity.to_csv(f'../results/{subject}pairwiseANOVA.csv')

if __name__ == '__main__':
    args, kwargs = utils.reader() 
    output = pointheatmap(*args, **kwargs)
    utils.writer(output)
