#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import matplotlib.pyplot as plt
import argparse
import sys
from omicsbuilder import utils

def stratify(df):
    '''
    If no arguments given then just stratify by all metadata
    '''
    meta = pd.read_csv("../results/meta.csv", index_col=0)
    metadf = df.join(meta[x].dropna(), how='inner').reset_index().set_index(['index', x])
    df = metadf.T.loc[metadf.sum(axis=0) != 0, metadf.sum(axis=1) !=0].sort_index().T
    return df

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('input_file', help='Path to the input file')
    args = parser.parse_args()
    args, kwargs = utils.reader() 
    output = stratify(*args, **kwargs)
    utils.writer(output)
