#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import matplotlib.pyplot as plt
import argparse
import sys
import utils

def varianceexplained(df, pval=True):
    import pandas as pd
    from skbio.stats.distance import permanova
    import numpy as np
    import skbio
    from scipy.spatial import distance
    df = df.loc[df.sum(axis=1) != 0, df.sum(axis=0) != 0]
    Ar_dist = distance.squareform(distance.pdist(df, metric="braycurtis"))
    DM_dist = skbio.stats.distance.DistanceMatrix(Ar_dist)
    result = permanova(DM_dist, df.index, permutations=10000)
    if pval:
        return result['p-value']
    else:
        return result['test statistic']


if __name__ == '__main__':
    args, kwargs = utils.reader() 
    output = main(*args, **kwargs)
    utils.writer(output)
